apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_SECRET_KEY: "<your-secret-key>"
  DJANGO_DEBUG: "True"  # или False для production
  DATABASE_URL: "sqlite:///db.sqlite3"
