# Generated by Django 5.0.7 on 2024-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_masyli_opasnosti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masyli',
            name='opasnosti',
            field=models.CharField(choices=[('KOLO', 'kolosalni'), ('OPAS', 'opasni'), ('NEIZ', 'neizvestni'), ('NEIT', 'neitral'), ('BEZO', 'bezopasni')], default='OPAS', max_length=4),
        ),
    ]
