# Generated by Django 5.0.7 on 2024-10-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_masyli_opasnosti'),
    ]

    operations = [
        migrations.AddField(
            model_name='supernaturalabilities',
            name='opasnosti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opasnosti_list', to='home.masyli'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supernaturalabilities',
            name='masyli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='home.masyli'),
        ),
    ]
