# Generated by Django 5.0.7 on 2024-10-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_supernaturalabilities_opasnosti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supernaturalabilities',
            name='opasnosti',
        ),
        migrations.AlterField(
            model_name='supernaturalabilities',
            name='masyli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.masyli'),
        ),
    ]
